<?php if ($countComment >= 1): ?>
    <h3>
    <?php echo $countComment > 1 ? $countComment . ' Comentarios' : 'Un Comentario'; ?>
</h3>
<?php endif; ?>

<?php foreach ($comentarios as $comment): ?>

        <div class="comment" id="<?php echo strtotime($comment->creado_at) ?>">
    <?php echo KuHelper::gravatar($comment->email, $comment->autor); ?>
            <p>
        <strong>
            <a href='<?php echo $comment->url ?>' title="<?php echo $comment->autor; ?>"><?php echo $comment->autor; ?></a>
        </strong>
    <?php echo $comment->comentario; ?>
</p>
    <?php echo strftime("%e de %B del %Y, a las %R", strtotime($comment->creado_at)); ?>

    </div>
<?php endforeach; ?>